//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Companies.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Hobbies = new HashSet<Hobby>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Hobby> Hobbies { get; set; }
    }
}
