//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourChat.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryOfChat
    {
        public CategoryOfChat()
        {
            this.Chats = new HashSet<Chat>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
    }
}
