//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourChat.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.ChatMessages = new HashSet<ChatMessage>();
            this.PrivateMessages = new HashSet<PrivateMessage>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
    
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
    }
}
