//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourChat.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        public int Id { get; set; }
        public int FromUser { get; set; }
        public int ToUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int MessageId { get; set; }
    
        public virtual FromUserId FromUserId { get; set; }
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
