//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourChat.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PrivateMessages = new HashSet<PrivateMessage>();
            this.Chats = new HashSet<Chat>();
            this.UserStatuses = new HashSet<UserStatus>();
        }
    
        public int Id { get; set; }
        public string NickName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual FromUserId FromUserId { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<UserStatus> UserStatuses { get; set; }
    }
}
